# Generated by Django 4.2.1 on 2023-06-08 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Codigo Producto')),
                ('nombreProducto', models.CharField(blank=True, max_length=50, verbose_name='Nombre Producto')),
                ('descripcionProducto', models.TextField(blank=True, max_length=200, verbose_name='Descripcion del Producto')),
                ('precio', models.IntegerField(blank=True, max_length=8, verbose_name='Precio')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codigo.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
