# Generated by Django 4.2.1 on 2023-06-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, verbose_name='Precio'),
        ),
    ]
