# Generated by Django 4.2.1 on 2023-06-09 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcionProducto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='nombre',
        ),
    ]
