# Generated by Django 4.2.1 on 2023-06-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0003_rename_descripcionproducto_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.TextField(blank=True, verbose_name='Precio'),
        ),
    ]
