# Generated by Django 4.2.1 on 2023-06-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0006_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precios',
        ),
    ]
