# Generated by Django 4.2.1 on 2023-07-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0007_rename_precio_producto_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, default=1, verbose_name='Cantidad de producto en inventario'),
            preserve_default=False,
        ),
    ]
