# Generated by Django 4.2.1 on 2023-07-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0010_boleta_envio_boleta_impuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usuario'),
        ),
    ]
