# Generated by Django 4.2.1 on 2023-07-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0011_boleta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.TextField(blank=True, max_length=200, verbose_name='Estado de la compra'),
        ),
    ]
